### ISSUE TITLE
Alignment of the constellation images

### ISSUE THREAD

**Issue by alexanderbock** [ccnyplanetarium/addons#2]
Reports originally from Alex @ NCMNS:

o	Some constellation art pictures are not lined up with their constellations, examples include but are not limited to; Andromeda is upside down, Lupus and Lynx have the head where the shoulder should be (image is too small), Mensa image is rotated about 90 degrees clockwise, and Pheonix is shifted about half its width to its left of the constellation.

**Comment by hedbergj** [comment]
Fixed a few orientations and other positional issues. Gave Virgo her Spica. Pulled on the tails of the bears a bit. Re Lynx: "... [Hevelius] used in it nineteen stars, and in explaining the title said that those who would examine the Lynx out to be lynx-eyed, in which he acknowledged the insignificance of the components."[1] Any way, it's a bit better now with the lines, but it would look too big I think if it extended the entire length. 

Thanks for the notes.

[1] Allen, RH Star Names - Their Lore and Meaning, 1899
